name: Tests

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }}
    strategy:
      matrix:
        swift: ["5.3", "5.4", "5.5", "5.6"]
    runs-on: macos-latest 
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -c release -Xswiftc -enable-testing --enable-test-discovery
